### ISSUE TITLE
Линии, состоящие из 1 точки

### ISSUE THREAD

**Issue by drnextgis** [nextgis/pywps.contour_lines_generator#2]
В результирующий шейп иногда попадают невалидные геометрии, например, состоящие из 1 точки:

```
OGRFeature(contour_lines):21
  cat (Integer) = 127
  level (Real) = 0.000000000000000
  LINESTRING Z (-0.416266006097561 54.3214842931937 0)
```

@KolesovDmitry, добавление ключа `cut=2` в вызов [r.contour](https://grass.osgeo.org/grass72/manuals/r.contour.html) позволит решить эту проблему?

**Comment by KolesovDmitry** [comment]
@drnextgis Да, должно решить проблему с линиями из одной точки. Но нет ли там других типов невалидных геометрий? Например, самопересечений?

**Comment by drnextgis** [comment]
Не проверял, пока столкнулись только с тем, что линия, состоящая из 1 точки не загружается в NGW.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/pywps.contour_lines_generator/commit/6ccd17918eca6020df50fc338a71c21b18c40c70
